test_params:
    alpha: 0.1
scrape_data_params:
    max_connections: 25
make_database_params:
    num_testing_rounds: 5
    refresh_views: true
build_features_params:
    max_lag_amount_player: 7
    max_lag_amount_team: 7
train_simple_linear_model_params:
    rerun_sql: true
    upper: 15
    lower: 2
train_robust_simple_linear_model_params:
    rerun_sql: true
    upper: 15
    lower: 2
train_nn_lstm_model_params:
    rerun_sql: true
    upper: 15
    lower: 2
    lstm_layer_size: 32
    normal_layer_size: 32
train_gbm_model_params:
    rerun_sql: true
    upper: 15
    lower: 2